import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "~/app/globals.css";

type Props = Readonly<{ children: React.ReactNode }>;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Not generated by create next app, but based on it",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
