import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '~/app/globals.css';

// this is needed for now, https://github.com/vercel/next.js/issues/63041
// eslint-disable-next-line quotes
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: `Next App`,
  description: `Not generated by create next app, but based on it`,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
